---
- hosts: myubuntuserver
  become: yes
  tasks:
  - name: i want to know host name
    command: hostname -f
    register: myresult

  - name:  i want to debug myresult
    debug:
       msg: "{{myresult}}"

