---
- hosts: all
  become: yes
  tasks:
  - name: i want to install web server on ubuntu
    apt:
      name:  apache2
      state: present
    when: ansible_os_family =="Debian"
      
  - name: i want to start web server on ubuntu
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"


  - name: i want to install web server on RedHat
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"


  - name: i want to start web server on RedHat
    service:
      name: httpd
      state: started
    when: ansible_os_family =="RedHat"









    